### PR TITLE
0.3.11 build 1 (downpin OFF toolkit)

### PR DESCRIPTION
**Pull request by j-wags**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by mattwthompson** [comment]
@conda-forge-admin, please rerender

**Comment by j-wags** [comment]
@mattwthompson Thanks for rerender - This is ready for review when you have a moment!

**Comment by mattwthompson** [comment]
@conda-forge-admin, please rerender

**Comment by mattwthompson** [comment]
Should `pymbar` be constrained as well? I'm using 68c9e37699044a78d51084708028aa2b286af4e5 / #10 as a reference, and the relevant diff (`git checkout jeff/main && git diff 68c9e37699044a78d51084708028aa2b286af4e`) is

```diff
diff --git a/recipe/meta.yaml b/recipe/meta.yaml
index b5e3d19..34ef0a1 100644
--- a/recipe/meta.yaml
+++ b/recipe/meta.yaml
@@ -7,10 +7,10 @@ package:
 
 source:
   url: https://github.com/openforcefield/{{ name }}/archive/v{{ version }}.tar.gz
-  sha256: bad05e7460286548ea1f38c1da9b01ea8b030fe5f67a4699ce75302cead267dc
+  sha256: a17c2878778e27374a07fb3f16a014fec112af2918fa70769359ab63e99d701f
 
 build:
-  number: 0
+  number: 1
   
 outputs:
   - name: {{ name|lower }}-base
@@ -24,15 +24,14 @@ outputs:
         - pip
       run:
         - python >=3.6
-        - openff-toolkit-base >=0.10.6
+        - openff-toolkit-base >=0.10.6,<0.11
         - openff-units >=0.1.4
         - numpy
         - pandas
-        - openmm
+        - openmm >=7.6
         - networkx
-        - pint
         - packmol
-        - pymbar >=3.0.5
+        - pymbar >=4.0.0
         - mdtraj >=1.9.3
         - dask >=2.7.0
         - distributed >=2.7.0
@@ -44,7 +43,8 @@ outputs:
         - rdkit
         - cmiles-base
         - python-dateutil
-        - pydantic
+        - pydantic <2.0.0a0
+
 
     test:
       imports:
@@ -81,3 +81,4 @@ about:
 extra:
   recipe-maintainers:
     - simonboothroyd
+    - mattwthompson
```

I'm pretty sure the existing 0.3.11 release will not work with `pymbar >=4`, going by chronology alone, and I don't have plans to make a 0.3.12 that fixes this. I think Pint should also be added back? The other constraints look good to me.

**Comment by mattwthompson** [comment]
Actually, I can see Pint in the logs since `openff-units` is snuck in somewhere. I can take or leave that change.

**Comment by j-wags** [comment]
Pint is pulled in by openff-units, so I think that's in good shape. 

> Should pymbar be constrained as well?

Ah, good call, I'll pin that. 

>  I don't have plans to make a 0.3.12 that fixes this

Agreed, no need to make that.

**Review by mattwthompson — APPROVED** [review]
LGTM (once tests pass again)!

**Comment by j-wags** [comment]
Thanks!

**Comment by j-wags** [comment]
Oh - I can't merge because I'm not a maintainer 🤦 Could you do it? I've also added myself to the maintainers to avoid this problem in the future.

**Comment by mattwthompson** [comment]
Instead of the simple solution, I've added you as a maintainer separately (https://github.com/conda-forge/openff-evaluator-feedstock/commit/c29187bf1cc72ca8c95bcebbbffddbda5b4caab5) - you should be able to merge now?

**Comment by j-wags** [comment]
Nice - Thanks!

**Pull request merged**
